import { precacheAndRoute } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { StaleWhileRevalidate } from "workbox-strategies";

// Precache files generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Cache images (you can expand this)
registerRoute(
  ({ request }) => request.destination === "image",
  new StaleWhileRevalidate({
    cacheName: "images-cache",
  })
);

// // Optional: cache API calls
// registerRoute(
//   ({ url }) => url.origin.includes("your-api-domain.com"),
//   new StaleWhileRevalidate({
//     cacheName: "api-cache",
//   })
// );

// Event listener for manual updates
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});
